### ISSUE TITLE
Dynamo crash when I try to create a new custom node from scratch

### ISSUE THREAD

**Issue by LuisaCPBR** [brencass/DynaStandard_public#7]
### What happened
I was creating a new custom node...I expected it to work normally, but right after filling in the name data and adding on category the Dynamo crash ... I imagine from the beginning of this description of error that may have to do with Dyna standart, is my guess correct?

### How To Reproduce Bug

Stack Trace

Object reference not set to an instance of an object.

   at DynaStandard.DynaStandardEvents.NewDynamoRunTypeChange(Object sender, PropertyChangedEventArgs e)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at Microsoft.Practices.Prism.ViewModel.NotificationObject.RaisePropertyChanged(String propertyName)
   at Dynamo.ViewModels.DynamoViewModel.set_ShowStartPage(Boolean value)
   at Dynamo.ViewModels.DynamoViewModel.ShowNewFunctionDialogAndMakeFunction(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### System Info
- Operating System: Microsoft Windows NT 10.0.18363.0
CLR: 4.0.30319.42000
- Dynamo Version: .... 2.3.0.5885
- DynaStandard Version: .... 1.0.6"

#### The more information you provide, the easier it will be to reproduce and fix the issue

https://github.com/DynamoDS/Dynamo/issues/10918

**Comment by brencass** [comment]
@LuisaCPBR  I am really sorry i have only just seen this issue as i never got any notification.

I was just about to push a new version out(V1.1.0) but i will hold it back and introduce a fix for the issue you are having in the next 24-48 hours.

**Comment by brencass** [comment]
This issue will be fixed in the latest version of DynaStandard which is V1.1.0. This has been uploaded to Github and will be pushed onto Dynamo Package website.
